name: Validate Data #add space here

on:
  push: pull_request #column removed

jobs:
  validate-data:
    runs-on: ubuntu-latest #add space here
    steps:
      - uses: actions/checkout@v2 #add space here
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Validate workflows   
      - run: |
          npm ci
          npx ts-node-script ./index.ts
        working-directory: ./script/validate-data